- name: Configuring apache2 and editing index.html file
  hosts: ubuntu 
  become: true
  tasks:
  - name: install apache
    apt:
     name: apache2
     state: present
  - name: Edit index.html file
    copy:
     content: "ANSIBLE TESTING\n"
     dest: /var/www/index.html
  - name: Restart apache2
    service:
     name: apache2
     state: started
  - name: check url response of server1
    uri:
     url: http://10.1.1.152
     status_code: 200 
