- name: this playbook is to create user using variable / variable file
  hosts: all 
  become: true
  vars_files:
    - user.yml
  tasks:
  - name: create user {{ user }}
    user:
     name: "{{ user }}"

