- name: this playbook install httpd using handlers & notify
  hosts: web
  become: true
  # gather_facts: no
  tasks:
  - name: install httpd
    yum:
     name: httpd
     state: present
     update_cache: yes
    notify: start apache
  
  handlers:
  - name: start apache
    service:
     name: httpd
     state: started

