- name: this playbook uninstall httpd
  hosts: all
  become: true
  #gather_facts: wont works
  tasks:
  - name: stop httpd service
    service:
     name: httpd
     state: stopped
    when: ansible_os_family == "RedHat"

  - name: unistall httpd
    yum:
     name: httpd
     state: removed
    when: ansible_os_family == "RedHat"

  - name: stop apache2 service
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: uninstall apache2
    apt:
     name: apache2
     state: absent 
    when: ansible_os_family == "Debian" 
